"""crear tablas equipos y partidos

Revision ID: 390b81d336d6
Revises: 
Create Date: 2026-06-18 19:23:09.765793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '390b81d336d6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('escudo_url', sa.String(length=255), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_equipos_id'), 'equipos', ['id'], unique=False)
    op.create_table('partidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipo_local_id', sa.Integer(), nullable=False),
    sa.Column('equipo_visitante_id', sa.Integer(), nullable=False),
    sa.Column('goles_local', sa.Integer(), nullable=True),
    sa.Column('goles_visitante', sa.Integer(), nullable=True),
    sa.Column('jugado', sa.Boolean(), nullable=False),
    sa.Column('fecha_juego', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['equipo_local_id'], ['equipos.id'], ),
    sa.ForeignKeyConstraint(['equipo_visitante_id'], ['equipos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partidos_id'), 'partidos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_partidos_id'), table_name='partidos')
    op.drop_table('partidos')
    op.drop_index(op.f('ix_equipos_id'), table_name='equipos')
    op.drop_table('equipos')
    # ### end Alembic commands ###
